require "user.options"
require "user.plugins"
require "user.bufferline"
-- require "user.cmp"
require "user.gitsigns"
require "user.colorscheme"
require "user.nvim-tree"
require "user.autopairs"
require "user.lsp"
require "user.keymappings"
